//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIAccessSpec) DeepCopyInto(out *APIAccessSpec) {
	*out = *in
	out.MasterKeyRef = in.MasterKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIAccessSpec.
func (in *APIAccessSpec) DeepCopy() *APIAccessSpec {
	if in == nil {
		return nil
	}
	out := new(APIAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallbackSpec) DeepCopyInto(out *CallbackSpec) {
	*out = *in
	if in.Success != nil {
		in, out := &in.Success, &out.Success
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Failure != nil {
		in, out := &in.Failure, &out.Failure
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Callbacks != nil {
		in, out := &in.Callbacks, &out.Callbacks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallbackSpec.
func (in *CallbackSpec) DeepCopy() *CallbackSpec {
	if in == nil {
		return nil
	}
	out := new(CallbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMGuardrail) DeepCopyInto(out *LiteLLMGuardrail) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMGuardrail.
func (in *LiteLLMGuardrail) DeepCopy() *LiteLLMGuardrail {
	if in == nil {
		return nil
	}
	out := new(LiteLLMGuardrail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMGuardrail) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMGuardrailList) DeepCopyInto(out *LiteLLMGuardrailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMGuardrail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMGuardrailList.
func (in *LiteLLMGuardrailList) DeepCopy() *LiteLLMGuardrailList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMGuardrailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMGuardrailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMGuardrailSpec) DeepCopyInto(out *LiteLLMGuardrailSpec) {
	*out = *in
	if in.DefaultOn != nil {
		in, out := &in.DefaultOn, &out.DefaultOn
		*out = new(bool)
		**out = **in
	}
	if in.APIBaseRef != nil {
		in, out := &in.APIBaseRef, &out.APIBaseRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.APIKeyRef != nil {
		in, out := &in.APIKeyRef, &out.APIKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Info != nil {
		in, out := &in.Info, &out.Info
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMGuardrailSpec.
func (in *LiteLLMGuardrailSpec) DeepCopy() *LiteLLMGuardrailSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMGuardrailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMGuardrailStatus) DeepCopyInto(out *LiteLLMGuardrailStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMGuardrailStatus.
func (in *LiteLLMGuardrailStatus) DeepCopy() *LiteLLMGuardrailStatus {
	if in == nil {
		return nil
	}
	out := new(LiteLLMGuardrailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServer) DeepCopyInto(out *LiteLLMMCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServer.
func (in *LiteLLMMCPServer) DeepCopy() *LiteLLMMCPServer {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMMCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServerList) DeepCopyInto(out *LiteLLMMCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMMCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServerList.
func (in *LiteLLMMCPServerList) DeepCopy() *LiteLLMMCPServerList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMMCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServerSpec) DeepCopyInto(out *LiteLLMMCPServerSpec) {
	*out = *in
	if in.AuthTokenRef != nil {
		in, out := &in.AuthTokenRef, &out.AuthTokenRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServerSpec.
func (in *LiteLLMMCPServerSpec) DeepCopy() *LiteLLMMCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServerStatus) DeepCopyInto(out *LiteLLMMCPServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServerStatus.
func (in *LiteLLMMCPServerStatus) DeepCopy() *LiteLLMMCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModel) DeepCopyInto(out *LiteLLMModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModel.
func (in *LiteLLMModel) DeepCopy() *LiteLLMModel {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModelList) DeepCopyInto(out *LiteLLMModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModelList.
func (in *LiteLLMModelList) DeepCopy() *LiteLLMModelList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModelSpec) DeepCopyInto(out *LiteLLMModelSpec) {
	*out = *in
	in.Params.DeepCopyInto(&out.Params)
	if in.Info != nil {
		in, out := &in.Info, &out.Info
		*out = new(ModelInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModelSpec.
func (in *LiteLLMModelSpec) DeepCopy() *LiteLLMModelSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModelStatus) DeepCopyInto(out *LiteLLMModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModelStatus.
func (in *LiteLLMModelStatus) DeepCopy() *LiteLLMModelStatus {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMParams) DeepCopyInto(out *LiteLLMParams) {
	*out = *in
	if in.APIBaseRef != nil {
		in, out := &in.APIBaseRef, &out.APIBaseRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.APIKeyRef != nil {
		in, out := &in.APIKeyRef, &out.APIKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.DropParams != nil {
		in, out := &in.DropParams, &out.DropParams
		*out = new(bool)
		**out = **in
	}
	if in.RPM != nil {
		in, out := &in.RPM, &out.RPM
		*out = new(int64)
		**out = **in
	}
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(int64)
		**out = **in
	}
	if in.Additional != nil {
		in, out := &in.Additional, &out.Additional
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMParams.
func (in *LiteLLMParams) DeepCopy() *LiteLLMParams {
	if in == nil {
		return nil
	}
	out := new(LiteLLMParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMProxy) DeepCopyInto(out *LiteLLMProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMProxy.
func (in *LiteLLMProxy) DeepCopy() *LiteLLMProxy {
	if in == nil {
		return nil
	}
	out := new(LiteLLMProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMProxyList) DeepCopyInto(out *LiteLLMProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMProxyList.
func (in *LiteLLMProxyList) DeepCopy() *LiteLLMProxyList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMProxySpec) DeepCopyInto(out *LiteLLMProxySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.APIAccess != nil {
		in, out := &in.APIAccess, &out.APIAccess
		*out = new(APIAccessSpec)
		**out = **in
	}
	if in.ModelSelector != nil {
		in, out := &in.ModelSelector, &out.ModelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(ProxyRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.GeneralSettings != nil {
		in, out := &in.GeneralSettings, &out.GeneralSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.RouterSettings != nil {
		in, out := &in.RouterSettings, &out.RouterSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.LitellmSettings != nil {
		in, out := &in.LitellmSettings, &out.LitellmSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Callbacks != nil {
		in, out := &in.Callbacks, &out.Callbacks
		*out = new(CallbackSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialList != nil {
		in, out := &in.CredentialList, &out.CredentialList
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultVertexConfig != nil {
		in, out := &in.DefaultVertexConfig, &out.DefaultVertexConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.FilesSettings != nil {
		in, out := &in.FilesSettings, &out.FilesSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.AssistantSettings != nil {
		in, out := &in.AssistantSettings, &out.AssistantSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.FinetuneSettings != nil {
		in, out := &in.FinetuneSettings, &out.FinetuneSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Prompts != nil {
		in, out := &in.Prompts, &out.Prompts
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorStoreRegistry != nil {
		in, out := &in.VectorStoreRegistry, &out.VectorStoreRegistry
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Service = in.Service
	in.Resources.DeepCopyInto(&out.Resources)
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMProxySpec.
func (in *LiteLLMProxySpec) DeepCopy() *LiteLLMProxySpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMProxyStatus) DeepCopyInto(out *LiteLLMProxyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMProxyStatus.
func (in *LiteLLMProxyStatus) DeepCopy() *LiteLLMProxyStatus {
	if in == nil {
		return nil
	}
	out := new(LiteLLMProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelInfo) DeepCopyInto(out *ModelInfo) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int64)
		**out = **in
	}
	if in.MaxInputTokens != nil {
		in, out := &in.MaxInputTokens, &out.MaxInputTokens
		*out = new(int64)
		**out = **in
	}
	if in.MaxOutputTokens != nil {
		in, out := &in.MaxOutputTokens, &out.MaxOutputTokens
		*out = new(int64)
		**out = **in
	}
	if in.SupportsFunctionCalling != nil {
		in, out := &in.SupportsFunctionCalling, &out.SupportsFunctionCalling
		*out = new(bool)
		**out = **in
	}
	if in.SupportsPromptCaching != nil {
		in, out := &in.SupportsPromptCaching, &out.SupportsPromptCaching
		*out = new(bool)
		**out = **in
	}
	if in.SupportsVision != nil {
		in, out := &in.SupportsVision, &out.SupportsVision
		*out = new(bool)
		**out = **in
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInfo.
func (in *ModelInfo) DeepCopy() *ModelInfo {
	if in == nil {
		return nil
	}
	out := new(ModelInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyRoute) DeepCopyInto(out *ProxyRoute) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ParentRefs != nil {
		in, out := &in.ParentRefs, &out.ParentRefs
		*out = make([]RouteParentRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyRoute.
func (in *ProxyRoute) DeepCopy() *ProxyRoute {
	if in == nil {
		return nil
	}
	out := new(ProxyRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyServiceSpec) DeepCopyInto(out *ProxyServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyServiceSpec.
func (in *ProxyServiceSpec) DeepCopy() *ProxyServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteParentRef) DeepCopyInto(out *RouteParentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteParentRef.
func (in *RouteParentRef) DeepCopy() *RouteParentRef {
	if in == nil {
		return nil
	}
	out := new(RouteParentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}
